// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: trial

#include "../ui.h"

void ui_Driving_screen_init(void)
{
ui_Driving = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Driving, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BG1 = lv_img_create(ui_Driving);
lv_img_set_src(ui_BG1, &ui_img_ebike_bg_png);
lv_obj_set_width( ui_BG1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BG1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BG1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BG1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BG1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Speed_Number_1 = lv_label_create(ui_Driving);
lv_obj_set_width( ui_Speed_Number_1, 153);
lv_obj_set_height( ui_Speed_Number_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Speed_Number_1, -26 );
lv_obj_set_y( ui_Speed_Number_1, 8 );
lv_obj_set_align( ui_Speed_Number_1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Speed_Number_1,"200");
lv_obj_set_style_text_color(ui_Speed_Number_1, lv_color_hex(0xFFE69C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Speed_Number_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Speed_Number_1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Speed_Number_1, &ui_font_Number, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_AQI = lv_label_create(ui_Driving);
lv_obj_set_width( ui_Label_AQI, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_AQI, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_AQI, -54 );
lv_obj_set_y( ui_Label_AQI, -60 );
lv_obj_set_align( ui_Label_AQI, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_AQI,"AQI");
lv_obj_set_style_text_color(ui_Label_AQI, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_AQI, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_AQI, &ui_font_Big, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Slider_Speed = lv_slider_create(ui_Driving);
lv_slider_set_value( ui_Slider_Speed, 75, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider_Speed)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider_Speed, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider_Speed, 123);
lv_obj_set_height( ui_Slider_Speed, 244);
lv_obj_set_x( ui_Slider_Speed, -100 );
lv_obj_set_y( ui_Slider_Speed, -1 );
lv_obj_set_align( ui_Slider_Speed, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Slider_Speed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Speed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Slider_Speed, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Speed, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Slider_Speed, &ui_img_speed_slider_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_bg_color(ui_Slider_Speed, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Speed, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Slider_Battery = lv_slider_create(ui_Driving);
lv_slider_set_value( ui_Slider_Battery, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider_Battery)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider_Battery, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider_Battery, 106);
lv_obj_set_height( ui_Slider_Battery, 235);
lv_obj_set_x( ui_Slider_Battery, -147 );
lv_obj_set_y( ui_Slider_Battery, 1 );
lv_obj_set_align( ui_Slider_Battery, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Slider_Battery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Battery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Slider_Battery, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Battery, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Slider_Battery, &ui_img_slider_battery_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_bg_color(ui_Slider_Battery, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Battery, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Group_Battery_Percent = lv_obj_create(ui_Driving);
lv_obj_set_width( ui_Group_Battery_Percent, 107);
lv_obj_set_height( ui_Group_Battery_Percent, 200);
lv_obj_set_align( ui_Group_Battery_Percent, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_Group_Battery_Percent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_Battery_Percent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_Battery_Percent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Number1 = lv_label_create(ui_Group_Battery_Percent);
lv_obj_set_width( ui_Label_Number1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Number1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Number1, 26 );
lv_obj_set_y( ui_Label_Number1, -2 );
lv_obj_set_align( ui_Label_Number1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Number1,"500.4#94aeb4");
lv_label_set_recolor(ui_Label_Number1,"true");
lv_obj_set_style_text_color(ui_Label_Number1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Number1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Number1, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Number2 = lv_label_create(ui_Group_Battery_Percent);
lv_obj_set_width( ui_Label_Number2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Number2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Number2, 10 );
lv_obj_set_y( ui_Label_Number2, lv_pct(12) );
lv_obj_set_align( ui_Label_Number2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Number2,"250.4#94aeb4");
lv_label_set_recolor(ui_Label_Number2,"true");
lv_obj_set_style_text_color(ui_Label_Number2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Number2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Number2, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Number3 = lv_label_create(ui_Group_Battery_Percent);
lv_obj_set_width( ui_Label_Number3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Number3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Number3, -10 );
lv_obj_set_y( ui_Label_Number3, lv_pct(27) );
lv_obj_set_align( ui_Label_Number3, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Number3,"150.4#94aeb4");
lv_label_set_recolor(ui_Label_Number3,"true");
lv_obj_set_style_text_color(ui_Label_Number3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Number3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Number3, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Number4 = lv_label_create(ui_Group_Battery_Percent);
lv_obj_set_width( ui_Label_Number4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Number4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Number4, -27 );
lv_obj_set_y( ui_Label_Number4, lv_pct(48) );
lv_obj_set_align( ui_Label_Number4, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Number4,"55.4#94aeb4");
lv_label_set_recolor(ui_Label_Number4,"true");
lv_obj_set_style_text_color(ui_Label_Number4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Number4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Number4, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Number5 = lv_label_create(ui_Group_Battery_Percent);
lv_obj_set_width( ui_Label_Number5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Number5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Number5, -13 );
lv_obj_set_y( ui_Label_Number5, lv_pct(66) );
lv_obj_set_align( ui_Label_Number5, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Number5,"35.4#94aeb4");
lv_label_set_recolor(ui_Label_Number5,"true");
lv_obj_set_style_text_color(ui_Label_Number5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Number5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Number5, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Number6 = lv_label_create(ui_Group_Battery_Percent);
lv_obj_set_width( ui_Label_Number6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Number6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Number6, 55 );
lv_obj_set_y( ui_Label_Number6, 162 );
lv_label_set_text(ui_Label_Number6,"12.0#94aeb4");
lv_label_set_recolor(ui_Label_Number6,"true");
lv_obj_set_style_text_color(ui_Label_Number6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Number6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Number6, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Number7 = lv_label_create(ui_Group_Battery_Percent);
lv_obj_set_width( ui_Label_Number7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Number7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Number7, 78 );
lv_obj_set_y( ui_Label_Number7, 188 );
lv_label_set_text(ui_Label_Number7,"0.0#94aeb4");
lv_label_set_recolor(ui_Label_Number7,"true");
lv_obj_set_style_text_color(ui_Label_Number7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Number7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Number7, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_Header = lv_obj_create(ui_Driving);
lv_obj_set_height( ui_Group_Header, 24);
lv_obj_set_width( ui_Group_Header, lv_pct(100));
lv_obj_set_align( ui_Group_Header, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Group_Header, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_Header, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Group_Header, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Group_Header, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Group_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Group_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Time_and_Date = lv_label_create(ui_Group_Header);
lv_obj_set_width( ui_Label_Time_and_Date, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Time_and_Date, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Time_and_Date, 5 );
lv_obj_set_y( ui_Label_Time_and_Date, 0 );
lv_obj_set_align( ui_Label_Time_and_Date, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label_Time_and_Date,"Tuesday, October 10, 2023 11:59 PM");
lv_obj_set_style_text_color(ui_Label_Time_and_Date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Time_and_Date, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Time_and_Date, &ui_font_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_pm2p5 = lv_label_create(ui_Group_Header);
lv_obj_set_width( ui_Label_pm2p5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_pm2p5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_pm2p5, -5 );
lv_obj_set_y( ui_Label_pm2p5, 3 );
lv_obj_set_align( ui_Label_pm2p5, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label_pm2p5,"PM2.5");
lv_obj_set_style_text_color(ui_Label_pm2p5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_pm2p5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_pm2p5, &ui_font_Big, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_Footer = lv_obj_create(ui_Driving);
lv_obj_set_height( ui_Group_Footer, 40);
lv_obj_set_width( ui_Group_Footer, lv_pct(100));
lv_obj_set_align( ui_Group_Footer, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_Group_Footer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_Footer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_Footer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Battery_Number = lv_label_create(ui_Group_Footer);
lv_obj_set_width( ui_Label_Battery_Number, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Battery_Number, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Battery_Number, -369 );
lv_obj_set_y( ui_Label_Battery_Number, 7 );
lv_obj_set_align( ui_Label_Battery_Number, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label_Battery_Number,"150.4 ug/m3");
lv_obj_set_style_text_color(ui_Label_Battery_Number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Battery_Number, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Battery_Number, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Battery_Number, &ui_font_Big, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button_Group = lv_obj_create(ui_Group_Footer);
lv_obj_set_width( ui_Button_Group, 236);
lv_obj_set_height( ui_Button_Group, 50);
lv_obj_set_align( ui_Button_Group, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_Button_Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button_Group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Driving = lv_obj_create(ui_Button_Group);
lv_obj_set_height( ui_BTN_Driving, 40);
lv_obj_set_width( ui_BTN_Driving, lv_pct(40));
lv_obj_set_align( ui_BTN_Driving, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_BTN_Driving, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BTN_Driving, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_Driving, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_BG1 = lv_img_create(ui_BTN_Driving);
lv_img_set_src(ui_BTN_BG1, &ui_img_menu_on_png);
lv_obj_set_width( ui_BTN_BG1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BTN_BG1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BTN_BG1, 0 );
lv_obj_set_y( ui_BTN_BG1, 1 );
lv_obj_set_align( ui_BTN_BG1, LV_ALIGN_CENTER );
lv_obj_add_state( ui_BTN_BG1, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_BTN_BG1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_BG1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_blend_mode(ui_BTN_BG1, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_BTN_BG1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_BTN_BG1, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_ICN_Driving = lv_img_create(ui_BTN_Driving);
lv_img_set_src(ui_ICN_Driving, &ui_img_5_png);
lv_obj_set_width( ui_ICN_Driving, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ICN_Driving, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ICN_Driving, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ICN_Driving, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ICN_Driving, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTN_Battery = lv_obj_create(ui_Button_Group);
lv_obj_set_height( ui_BTN_Battery, 40);
lv_obj_set_width( ui_BTN_Battery, lv_pct(40));
lv_obj_set_align( ui_BTN_Battery, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BTN_Battery, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BTN_Battery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_Battery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_BG2 = lv_img_create(ui_BTN_Battery);
lv_img_set_src(ui_BTN_BG2, &ui_img_menu_on_png);
lv_obj_set_width( ui_BTN_BG2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BTN_BG2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BTN_BG2, 0 );
lv_obj_set_y( ui_BTN_BG2, 1 );
lv_obj_set_align( ui_BTN_BG2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTN_BG2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_BG2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_blend_mode(ui_BTN_BG2, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_BTN_BG2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_BTN_BG2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_ICN_Battery = lv_img_create(ui_BTN_Battery);
lv_img_set_src(ui_ICN_Battery, &ui_img_4_png);
lv_obj_set_width( ui_ICN_Battery, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ICN_Battery, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ICN_Battery, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ICN_Battery, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ICN_Battery, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTN_Lock = lv_obj_create(ui_Button_Group);
lv_obj_set_height( ui_BTN_Lock, 40);
lv_obj_set_width( ui_BTN_Lock, lv_pct(40));
lv_obj_set_align( ui_BTN_Lock, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_BTN_Lock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BTN_Lock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_Lock, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_BG3 = lv_img_create(ui_BTN_Lock);
lv_img_set_src(ui_BTN_BG3, &ui_img_menu_on_png);
lv_obj_set_width( ui_BTN_BG3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BTN_BG3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BTN_BG3, 0 );
lv_obj_set_y( ui_BTN_BG3, 1 );
lv_obj_set_align( ui_BTN_BG3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTN_BG3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_BG3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_blend_mode(ui_BTN_BG3, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_BTN_BG3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_BTN_BG3, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_ICN_Lock = lv_img_create(ui_BTN_Lock);
lv_img_set_src(ui_ICN_Lock, &ui_img_6_png);
lv_obj_set_width( ui_ICN_Lock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ICN_Lock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ICN_Lock, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ICN_Lock, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ICN_Lock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Group_room1 = lv_obj_create(ui_Driving);
lv_obj_set_width( ui_Group_room1, 260);
lv_obj_set_height( ui_Group_room1, 200);
lv_obj_set_x( ui_Group_room1, 0 );
lv_obj_set_y( ui_Group_room1, -10 );
lv_obj_set_align( ui_Group_room1, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_Group_room1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_room1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_room1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_Title = lv_obj_create(ui_Group_room1);
lv_obj_set_width( ui_Group_Title, 260);
lv_obj_set_height( ui_Group_Title, 46);
lv_obj_set_align( ui_Group_Title, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Group_Title, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_Title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_Title, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Title_BG = lv_img_create(ui_Group_Title);
lv_img_set_src(ui_Title_BG, &ui_img_menu_line_png);
lv_obj_set_width( ui_Title_BG, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Title_BG, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Title_BG, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_Title_BG, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Title_BG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_Indoor_Air_Quality_Information = lv_label_create(ui_Group_Title);
lv_obj_set_width( ui_Label_Indoor_Air_Quality_Information, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Indoor_Air_Quality_Information, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Indoor_Air_Quality_Information, -6 );
lv_obj_set_y( ui_Label_Indoor_Air_Quality_Information, 0 );
lv_obj_set_align( ui_Label_Indoor_Air_Quality_Information, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label_Indoor_Air_Quality_Information,"ICT-3C IAQ Information");
lv_obj_set_style_text_color(ui_Label_Indoor_Air_Quality_Information, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Indoor_Air_Quality_Information, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Indoor_Air_Quality_Information, &ui_font_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_IAQ_temp_hum_cat = lv_label_create(ui_Group_room1);
lv_obj_set_width( ui_Label_IAQ_temp_hum_cat, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_IAQ_temp_hum_cat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_IAQ_temp_hum_cat, -21 );
lv_obj_set_y( ui_Label_IAQ_temp_hum_cat, -23 );
lv_obj_set_align( ui_Label_IAQ_temp_hum_cat, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label_IAQ_temp_hum_cat,"Temperature: 26.74 °C\nHumidity: 68.01 %\nCategory: Unhealthy");
lv_obj_set_style_text_color(ui_Label_IAQ_temp_hum_cat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_IAQ_temp_hum_cat, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_IAQ_temp_hum_cat, &ui_font_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_IAQ_advisory = lv_label_create(ui_Group_room1);
lv_obj_set_width( ui_Label_IAQ_advisory, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_IAQ_advisory, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_IAQ_advisory, -7 );
lv_obj_set_y( ui_Label_IAQ_advisory, 53 );
lv_obj_set_align( ui_Label_IAQ_advisory, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label_IAQ_advisory,"\"Some members of the general\npublic may experience \nhealth effects; members of\nsensitive groups may\nexperience more serious health \neffects.");
lv_obj_set_style_text_color(ui_Label_IAQ_advisory, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_IAQ_advisory, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_IAQ_advisory, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_room2 = lv_obj_create(ui_Driving);
lv_obj_set_width( ui_Group_room2, 260);
lv_obj_set_height( ui_Group_room2, 200);
lv_obj_set_x( ui_Group_room2, 0 );
lv_obj_set_y( ui_Group_room2, -10 );
lv_obj_set_align( ui_Group_room2, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_Group_room2, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Group_room2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_room2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_room2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_Title1 = lv_obj_create(ui_Group_room2);
lv_obj_set_width( ui_Group_Title1, 260);
lv_obj_set_height( ui_Group_Title1, 46);
lv_obj_set_align( ui_Group_Title1, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Group_Title1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_Title1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_Title1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Title_BG1 = lv_img_create(ui_Group_Title1);
lv_img_set_src(ui_Title_BG1, &ui_img_menu_line_png);
lv_obj_set_width( ui_Title_BG1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Title_BG1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Title_BG1, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_Title_BG1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Title_BG1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_Battery_Information = lv_label_create(ui_Group_Title1);
lv_obj_set_width( ui_Label_Battery_Information, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Battery_Information, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Battery_Information, -5 );
lv_obj_set_y( ui_Label_Battery_Information, 0 );
lv_obj_set_align( ui_Label_Battery_Information, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label_Battery_Information,"EMB-Lab IAQ Information");
lv_obj_set_style_text_color(ui_Label_Battery_Information, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Battery_Information, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Battery_Information, &ui_font_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_IAQ_advisory1 = lv_label_create(ui_Group_room2);
lv_obj_set_width( ui_Label_IAQ_advisory1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_IAQ_advisory1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_IAQ_advisory1, -7 );
lv_obj_set_y( ui_Label_IAQ_advisory1, 54 );
lv_obj_set_align( ui_Label_IAQ_advisory1, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label_IAQ_advisory1,"\"Air quality is acceptable. How-\never, there may be a risk for \nsome people, particularly those\nwho are unusually sensitive to\nair pollution.\"");
lv_obj_set_style_text_color(ui_Label_IAQ_advisory1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_IAQ_advisory1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_IAQ_advisory1, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_IAQ_temp_hum_cat1 = lv_label_create(ui_Group_room2);
lv_obj_set_width( ui_Label_IAQ_temp_hum_cat1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_IAQ_temp_hum_cat1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_IAQ_temp_hum_cat1, -21 );
lv_obj_set_y( ui_Label_IAQ_temp_hum_cat1, -23 );
lv_obj_set_align( ui_Label_IAQ_temp_hum_cat1, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label_IAQ_temp_hum_cat1,"Temperature: 22.34 °C\nHumidity: 49.85 %\nCategory: Moderate");
lv_obj_set_style_text_color(ui_Label_IAQ_temp_hum_cat1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_IAQ_temp_hum_cat1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_IAQ_temp_hum_cat1, &ui_font_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_room3 = lv_obj_create(ui_Driving);
lv_obj_set_width( ui_Group_room3, 260);
lv_obj_set_height( ui_Group_room3, 200);
lv_obj_set_x( ui_Group_room3, 0 );
lv_obj_set_y( ui_Group_room3, -10 );
lv_obj_set_align( ui_Group_room3, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_Group_room3, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Group_room3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_room3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_room3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Group_Title2 = lv_obj_create(ui_Group_room3);
lv_obj_set_width( ui_Group_Title2, 260);
lv_obj_set_height( ui_Group_Title2, 46);
lv_obj_set_align( ui_Group_Title2, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Group_Title2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Group_Title2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Group_Title2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Title_BG2 = lv_img_create(ui_Group_Title2);
lv_img_set_src(ui_Title_BG2, &ui_img_menu_line_png);
lv_obj_set_width( ui_Title_BG2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Title_BG2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Title_BG2, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_Title_BG2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Title_BG2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_Unlock = lv_label_create(ui_Group_Title2);
lv_obj_set_width( ui_Label_Unlock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Unlock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Unlock, -6 );
lv_obj_set_y( ui_Label_Unlock, 0 );
lv_obj_set_align( ui_Label_Unlock, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label_Unlock,"Office IAQ Information");
lv_obj_set_style_text_color(ui_Label_Unlock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Unlock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Unlock, &ui_font_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_IAQ_temp_hum_cat2 = lv_label_create(ui_Group_room3);
lv_obj_set_width( ui_Label_IAQ_temp_hum_cat2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_IAQ_temp_hum_cat2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_IAQ_temp_hum_cat2, -21 );
lv_obj_set_y( ui_Label_IAQ_temp_hum_cat2, -23 );
lv_obj_set_align( ui_Label_IAQ_temp_hum_cat2, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label_IAQ_temp_hum_cat2,"Temperature: 24.54 °C\nHumidity: 35.95 %\nCategory: Good");
lv_obj_set_style_text_color(ui_Label_IAQ_temp_hum_cat2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_IAQ_temp_hum_cat2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_IAQ_temp_hum_cat2, &ui_font_Medium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_IAQ_advisory2 = lv_label_create(ui_Group_room3);
lv_obj_set_width( ui_Label_IAQ_advisory2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_IAQ_advisory2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_IAQ_advisory2, -12 );
lv_obj_set_y( ui_Label_IAQ_advisory2, 50 );
lv_obj_set_align( ui_Label_IAQ_advisory2, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label_IAQ_advisory2,"\"Air quality is satisfactory, and\nair pollution poses little or no\nrisk.\"");
lv_obj_set_style_text_color(ui_Label_IAQ_advisory2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_IAQ_advisory2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_IAQ_advisory2, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BTN_BG1, ui_event_BTN_BG1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_BG2, ui_event_BTN_BG2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_BG3, ui_event_BTN_BG3, LV_EVENT_ALL, NULL);

}
