// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: trial

#ifndef _TRIAL_UI_H
#define _TRIAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void Particle1_Animation( lv_obj_t *TargetObject, int delay);
void Particle2_Animation( lv_obj_t *TargetObject, int delay);
void Particle3_Animation( lv_obj_t *TargetObject, int delay);
void Fash_Animation( lv_obj_t *TargetObject, int delay);
void Wave1_Animation( lv_obj_t *TargetObject, int delay);
void Wave2_Animation( lv_obj_t *TargetObject, int delay);
void Off_Animation( lv_obj_t *TargetObject, int delay);
void On_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Driving
void ui_Driving_screen_init(void);
extern lv_obj_t *ui_Driving;
extern lv_obj_t *ui_BG1;
extern lv_obj_t *ui_Speed_Number_1;
extern lv_obj_t *ui_Label_AQI;
extern lv_obj_t *ui_Slider_Speed;
extern lv_obj_t *ui_Slider_Battery;
extern lv_obj_t *ui_Group_Battery_Percent;
extern lv_obj_t *ui_Label_Number1;
extern lv_obj_t *ui_Label_Number2;
extern lv_obj_t *ui_Label_Number3;
extern lv_obj_t *ui_Label_Number4;
extern lv_obj_t *ui_Label_Number5;
extern lv_obj_t *ui_Label_Number6;
extern lv_obj_t *ui_Label_Number7;
extern lv_obj_t *ui_Group_Header;
extern lv_obj_t *ui_Label_Time_and_Date;
extern lv_obj_t *ui_Label_pm2p5;
extern lv_obj_t *ui_Group_Footer;
extern lv_obj_t *ui_Label_Battery_Number;
extern lv_obj_t *ui_Button_Group;
extern lv_obj_t *ui_BTN_Driving;
void ui_event_BTN_BG1( lv_event_t * e);
extern lv_obj_t *ui_BTN_BG1;
extern lv_obj_t *ui_ICN_Driving;
extern lv_obj_t *ui_BTN_Battery;
void ui_event_BTN_BG2( lv_event_t * e);
extern lv_obj_t *ui_BTN_BG2;
extern lv_obj_t *ui_ICN_Battery;
extern lv_obj_t *ui_BTN_Lock;
void ui_event_BTN_BG3( lv_event_t * e);
extern lv_obj_t *ui_BTN_BG3;
extern lv_obj_t *ui_ICN_Lock;
extern lv_obj_t *ui_Group_room1;
extern lv_obj_t *ui_Group_Title;
extern lv_obj_t *ui_Title_BG;
extern lv_obj_t *ui_Label_Indoor_Air_Quality_Information;
extern lv_obj_t *ui_Label_IAQ_temp_hum_cat;
extern lv_obj_t *ui_Label_IAQ_advisory;
extern lv_obj_t *ui_Group_room2;
extern lv_obj_t *ui_Group_Title1;
extern lv_obj_t *ui_Title_BG1;
extern lv_obj_t *ui_Label_Battery_Information;
extern lv_obj_t *ui_Label_IAQ_advisory1;
extern lv_obj_t *ui_Label_IAQ_temp_hum_cat1;
extern lv_obj_t *ui_Group_room3;
extern lv_obj_t *ui_Group_Title2;
extern lv_obj_t *ui_Title_BG2;
extern lv_obj_t *ui_Label_Unlock;
extern lv_obj_t *ui_Label_IAQ_temp_hum_cat2;
extern lv_obj_t *ui_Label_IAQ_advisory2;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_ebike_bg_png);   // assets\ebike_bg.png
LV_IMG_DECLARE( ui_img_speed_slider_png);   // assets\speed_slider.png
LV_IMG_DECLARE( ui_img_slider_battery_png);   // assets\slider_battery.png
LV_IMG_DECLARE( ui_img_menu_on_png);   // assets\menu_on.png
LV_IMG_DECLARE( ui_img_5_png);   // assets\5.png
LV_IMG_DECLARE( ui_img_4_png);   // assets\4.png
LV_IMG_DECLARE( ui_img_6_png);   // assets\6.png
LV_IMG_DECLARE( ui_img_menu_line_png);   // assets\menu_line.png
LV_IMG_DECLARE( ui_img_1_png);   // assets\1.png
LV_IMG_DECLARE( ui_img_2_png);   // assets\2.png
LV_IMG_DECLARE( ui_img_3_png);   // assets\3.png
LV_IMG_DECLARE( ui_img_laboratory_6552495_png);   // assets\laboratory_6552495.png
LV_IMG_DECLARE( ui_img_1205723570);   // assets\office-building_1518379.png
LV_IMG_DECLARE( ui_img_particle_1_png);   // assets\particle_1.png
LV_IMG_DECLARE( ui_img_particle_2_png);   // assets\particle_2.png
LV_IMG_DECLARE( ui_img_particle_3_png);   // assets\particle_3.png
LV_IMG_DECLARE( ui_img_training_2849198_png);   // assets\training_2849198.png
LV_IMG_DECLARE( ui_img_water_1_png);   // assets\water_1.png
LV_IMG_DECLARE( ui_img_water_2_png);   // assets\water_2.png

LV_FONT_DECLARE( ui_font_Big);
LV_FONT_DECLARE( ui_font_Medium);
LV_FONT_DECLARE( ui_font_Number);
LV_FONT_DECLARE( ui_font_Small);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
